VERSION TVOID 0V


VOID TVOID 0V
PUSH TNUMBER 0
PUSH TSTRING 
PUSH TSTRING !
PUSH TSTRING !
VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
PRINT TNUMBER 32
PRINTLN TNUMBER 32
PRINTLN TNUMBER  
PRINTLN TVOID 0V
PUSH TNUMBER 0
PUSH TNUMBER 0
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TCHARACTER 'c'
PRINTLN TSTRING "Hello World!"
PUSH TBOOLEAN false
PUSH TBOOLEAN false
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TNUMBER 4
PRINTLN TNUMBER 2
PRINTLN TNUMBER 3
PRINTLN TNUMBER 3
PRINTLN TNUMBER 2
PRINTLN TNUMBER 3
PRINTLN TNUMBER 4
PRINTLN TSTRING "\n"
PRINTLN TCHARACTER 'N'
PRINTLN TCHARACTER ' '
PRINTLN TCHARACTER 'ñ'
PRINTLN TCHARACTER ''
PRINTLN TCHARACTER ' '
PRINTLN TCHARACTER ' '
PRINTLN TCHARACTER ' '
PRINTLN TCHARACTER '('
PRINTLN TCHARACTER ' '
PRINTLN TCHARACTER '&'
PRINTLN TCHARACTER ' '
PRINTLN TSTRING "Hello World!"
PRINTLN TSTRING "Hello World!"
QUIT TVOID 

END TVOID 0V