VERSION TVOID 1


FDECL TSTRING "a"
FRETS TVOID 0V
FERETS TVOID 0V
FPARAMS TVOID 0V
FEPARAMS TVOID 0V
FEDECL TVOID 0V

FDEF TSTRING "a"
FDEF2 TVOID 0V


PRINTLN TSTRING "a()."

FRET TVOID 0V


FEDEF2 TVOID 0V
FEDEF TVOID 0V

FCALL TSTRING "a"
FCPARAMS TVOID 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""


FDECL TSTRING "abc"
FRETS TVOID 0V
VAR TSTRING 0V
FERETS TVOID 0V
FPARAMS TVOID 0V
FEPARAMS TVOID 0V
FEDECL TVOID 0V

FDEF TSTRING "abc"
RETURNF2 TSTRING 0V
FDEF2 TVOID 0V


PRINTLN TSTRING "Hello World!"
PRINTLN TSTRING "abc"

;ALOAD TSTRING "abc"
;RNUM TNUMBER 0
;RETURNF TSTRING 0V

FRET TVOID 0V

FEDEF2 TVOID 0V
FEDEF TVOID 0V

FCALL TSTRING "abc"
FCPARAMS TVOID 0V
RETURNF2 TSTRING 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FDECL TSTRING "abc2"
FRETS TVOID 0V
VAR TSTRING 0V
FERETS TVOID 0V
FPARAMS TVOID 0V
VAR TSTRING "a"
FEPARAMS TVOID 0V
FEDECL TVOID 0V

FDEF TSTRING "abc2"
RETURNF2 TSTRING 0V
PNUM TNUMBER 0
PARAMF3 TSTRING 0V
FDEF2 TVOID 0V


PRINTLN TSTRING "Hello World 2!"
PNUM TNUMBER 0
PARAMF2 TVOID 0V
PRINTLN TVOID 0V

FRET TVOID 0V

FEDEF2 TVOID 0V
FEDEF TVOID 0V

;FNAME TSTRING "abc"
;RNUM TNUMBER 0
;RETURNV TVOID 0V

;PRINTLN TVOID 0V

FCALL TSTRING "abc2"
FCPARAMS TVOID 0V
RETURNF2 TSTRING 0V
PNUM TNUMBER 0
PARAMF TSTRING "abc2_3"
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FDECL TSTRING "abc3"
FRETS TVOID 0V
VAR TSTRING 0V
VAR TNUMBER 0V
FERETS TVOID 0V
FPARAMS TVOID 0V
VAR TSTRING "a"
VAR TSTRING "b"
FEPARAMS TVOID 0V
FEDECL TVOID 0V

FDEF TSTRING "abc3"
RETURNF2 TSTRING 0V
RETURNF2 TNUMBER 0V
PARAMF3 TSTRING 0V
PARAMF3 TSTRING 0V
FDEF2 TVOID 0V


PRINTLN TSTRING "Hello World 3!"

FRET TVOID 0V

FEDEF2 TVOID 0V
FEDEF TVOID 0V

FCALL TSTRING "abc3"
FCPARAMS TVOID 0V
RETURNF2 TSTRING 0V
RETURNF2 TNUMBER 0V
PNUM TNUMBER 0
PARAMF TSTRING "abc3_3"
PNUM TNUMBER 1
PARAMF TSTRING "abc3_4"
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FDECL TSTRING "abc4"
FRETS TVOID 0V
FERETS TVOID 0V
FPARAMS TVOID 0V
FEPARAMS TVOID 0V
FEDECL TVOID 0V

FDEF TSTRING "abc4"
FDEF2 TVOID 0V

PRINTLN TSTRING "Hello World 4!"

FCALL2 TSTRING "abc"
FCPARAMS2 TVOID 0V
RETURNF2 TSTRING 0V
FECPARAMS2 TVOID 0V
FECALL2 TVOID 0V

FRET TVOID 0V

FEDEF2 TVOID 0V
FEDEF TVOID 0V

FCALL TSTRING "abc4"
FCPARAMS TVOID 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V

;FNCNEW TVOID 0V
;ALOAD TSTRING "funcf"
;FNCSNAME TVOID 0V
;FNCSDEF TSTRING "func"
;FNCSTORE TVOID 0V
;FNCDELETE TVOID 0V

;FNCNEW TVOID 0V
;ALOAD TSTRING "funcf"
;FNCSNAME TVOID 0V
;FNCSRET TVOID 0V
;FNCSDEF TSTRING "func2"
;FNCSTORE TVOID 0V
;FNCDELETE TVOID 0V


;PRINTLN TSTRING ""

;FCALL TSTRING "funcf"
;FCPARAMS TVOID 0V
;FECPARAMS TVOID 0V
;FECALL TVOID 0V

;PRINTLN TSTRING ""

;FCALL TSTRING "funcf"
;FCPARAMS TVOID 0V
;RETURNF2 TVOID 0V
;FECPARAMS TVOID 0V
;FECALL TVOID 0V




QUIT TVOID 0


;LBL TSTRING "func"
; PRINTLN TSTRING "Hello from new() function."
; FRET TVOID 0V

;LBL TSTRING "func2"
; PRINTLN TSTRING "Hello from new2() function."
; FRET TVOID 0V


END TVOID 0V