VERSION TVOID 1


FNCNEW TVOID 0V
ALOAD TSTRING "a"
FNCSNAME TVOID 0V
FNCSDEF TSTRING "a"
FNCSTORE TVOID 0V
FNCDELETE TVOID 0V

FNCNEW TVOID 0V
ALOAD TSTRING ""
FNCSRET TSTRING 0V
ALOAD TSTRING "abc"
FNCSNAME TVOID 0V
FNCSDEF TSTRING "abc"
FNCSTORE TVOID 0V
FNCDELETE TVOID 0V

FNCNEW TVOID 0V
ALOAD TSTRING ""
FNCSRET TSTRING 0V
FNCSPARAM TSTRING 0V
ALOAD TSTRING "abc2"
FNCSNAME TVOID 0V
FNCSDEF TSTRING "abc2"
FNCSTORE TVOID 0V
FNCDELETE TVOID 0V

FNCNEW TVOID 0V
RNUM TNUMBER 0
ALOAD TSTRING ""
FNCSRET TSTRING 0V
RNUM TNUMBER 1
ALOAD TNUMBER 0
FNCSRET TNUMBER 0V
ALOAD TSTRING ""
PNUM TNUMBER 0
FNCSPARAM TSTRING 0V
PNUM TNUMBER 1
FNCSPARAM TSTRING 0V
ALOAD TSTRING "abc3"
FNCSNAME TVOID 0V
FNCSDEF TSTRING "abc3"
FNCSTORE TVOID 0V
FNCDELETE TVOID 0V

FNCNEW TVOID 0V
ALOAD TSTRING "abc4"
FNCSNAME TVOID 0V
FNCSDEF TSTRING "abc4"
FNCSTORE TVOID 0V
FNCDELETE TVOID 0V

FNCNEW TVOID 0V
ALOAD TSTRING "funcf"
FNCSNAME TVOID 0V
FNCSDEF TSTRING "func"
FNCSTORE TVOID 0V
FNCDELETE TVOID 0V

FNCNEW TVOID 0V
RNUM TNUMBER 0
ALOAD TSTRING ""
FNCSRET TSTRING 0V
ALOAD TSTRING "funcf"
FNCSNAME TVOID 0V
FNCSDEF TSTRING "func2"
FNCSTORE TVOID 0V
FNCDELETE TVOID 0V


;PRINTLN TSTRING ""

FCALL TSTRING "a"
FCPARAMS TVOID 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FCALL TSTRING "abc"
FCPARAMS TVOID 0V
RETURNF2 TSTRING 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FCALL TSTRING "abc2"
FCPARAMS TVOID 0V
RETURNF2 TSTRING 0V
PNUM TNUMBER 0
PARAMF TSTRING "abc2_3"
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FCALL TSTRING "abc3"
FCPARAMS TVOID 0V
RNUM TNUMBER 0
RETURNF2 TSTRING 0V
RNUM TNUMBER 1
RETURNF2 TNUMBER 0V
PNUM TNUMBER 0
PARAMF TSTRING "abc3_3"
PNUM TNUMBER 1
PARAMF TSTRING "abc3_4"
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FCALL TSTRING "abc4"
FCPARAMS TVOID 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V

FCALL TSTRING "funcf"
FCPARAMS TVOID 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V

PRINTLN TSTRING ""

FCALL TSTRING "funcf"
FCPARAMS TVOID 0V
RNUM TNUMBER 0
RETURNF2 TSTRING 0V
FECPARAMS TVOID 0V
FECALL TVOID 0V




QUIT TVOID 0


LBL TSTRING "a"
 PRINTLN TSTRING "a()."
 FRET TVOID 0V

LBL TSTRING "abc"
 PRINTLN TSTRING "Hello World!"
 PRINTLN TSTRING "abc"

 FRET TVOID 0V

LBL TSTRING "abc2"
 PRINTLN TSTRING "Hello World 2!"
 PNUM TNUMBER 0
 PARAMF2 TVOID 0V
 PRINTLN TVOID 0V

 FRET TVOID 0V

LBL TSTRING "abc3"
 PRINTLN TSTRING "Hello World 4!"

 FCALL2 TSTRING "abc"
 FCPARAMS2 TVOID 0V
 RETURNF3 TSTRING 0V
 FECPARAMS2 TVOID 0V
 FECALL2 TVOID 0V

 FRET TVOID 0V



LBL TSTRING "abc4"
 PRINTLN TSTRING "Hello World 3!"

 FRET TVOID 0V

LBL TSTRING "func"
 PRINTLN TSTRING "Hello from new() function."
 FRET TVOID 0V

LBL TSTRING "func2"
 PRINTLN TSTRING "Hello from new2() function."
 FRET TVOID 0V



END TVOID 0V