VERSION TVOID 0V


ALOAD TNUMBER 0
VSTORE TVOID 0V
PRINT TSTRING "Enter a number: "
READ TNUMBER 0V
ATOC TVOID 0V
VADD TVOID 0
SWITCH TVOID 0V
STOREA TVOID 0V
PRINT TSTRING "a: "
VADD TVOID 0
ADD2V TVOID 0V
PRINTLN TVOID 0V
VADD TVOID 0
ADD2V TVOID 0V
ATOC TVOID 0V
ALOAD TNUMBER 33
SWITCH TVOID 0V
EQU TVOID 0V
CGOTOL TVOID 0
GOTOL TVOID 1
LBL TVOID 0V
PRINTLN TSTRING "33"
GOTOL TVOID 2
LBL TVOID 0V
PRINTLN TSTRING "Not 33"
GOTOL TVOID 2
LBL TVOID 0V
VOID TVOID 0V
QUIT TVOID 0


END TVOID 0V