VERSION TVOID 1


STRUCT TSTRING "a"
STRUCTVAR TSTRING "a"
STRUCTVAR TSTRING "b"
ENDSTRUCT TVOID 0V
STRUCTNAME TSTRING "a"
STRUCTD TSTRING "abc"
STRUCTNAME TSTRING "a"
STRUCTONAME TSTRING "abc"
STRUCTUSE TSTRING "a"
ALOAD TNUMBER 2.000000
STRUCTPUT TVOID 0V
STRUCTNAME TSTRING "a"
STRUCTONAME TSTRING "abc"
STRUCTUSE TSTRING "b"
ALOAD TSTRING "Hello World!"
STRUCTPUT TVOID 0V
STRUCTUSING TVOID 0V
PRINTLN TVOID 0V
STRUCTUSINGNAME TVOID 0V
PRINTLN TVOID 0V
STRUCTGET TVOID 0V
PRINTLN TVOID 0V
STRUCTTYPE TVOID 0V
PRINTLN TVOID 0V
STRUCTNAME2 TVOID 0V
PRINTLN TVOID 0V
UNION TSTRING "a"
UNIONVAR TSTRING "a"
UNIONVAR TSTRING "b"
ENDUNION TVOID 0V
UNIONNAME TSTRING "a"
UNIOND TSTRING "uniona"
UNIONNAME TSTRING "a"
UNIONONAME TSTRING "uniona"
UNIONUSE TSTRING "a"
ALOAD TSTRING "Hello World!"
UNIONPUT TVOID 0V
UNIONGET TVOID 0V
PRINTLN TVOID 0V
UNIONNAME TSTRING "a"
UNIONONAME TSTRING "uniona"
UNIONUSE TSTRING "b"
ALOAD TSTRING "Hello Tree"
UNIONPUT TVOID 0V
UNIONGET TVOID 0V
PRINTLN TVOID 0V
UNIONUSE TSTRING "a"
UNIONGET TVOID 0V
PRINTLN TVOID 0V
UNIONUSING TVOID 0V
PRINTLN TVOID 0V
UNIONUSINGNAME TVOID 0V
PRINTLN TVOID 0V
UNIONTYPE TVOID 0V
PRINTLN TVOID 0V
UNIONNAME2 TVOID 0V
PRINTLN TVOID 0V
QUIT TVOID 0


END TVOID 0V