VERSION TVOID 0V


PRINTLN TSTRING "Defining an enum..."
ESTART TSTRING "a"
ENAME TSTRING "a"
ENAME TSTRING "b"
ENAME TSTRING "c"
EEND TVOID 0V
PRINTLN TSTRING "Implementing an enum..."
ENUMS TSTRING "a"
ENUM TSTRING "c"
SENUM TSTRING "a"
PRINTLN TSTRING "Testing load and store..."
PRINT TSTRING "enum a: "
EPREP TSTRING "a"
LOADE TVOID 0V
PRINTLN TVOID 0V
PRINTLN TSTRING "Quitting..."
QUIT TVOID 0


END TVOID 0V