VERSION TVOID 0V


PRINTLN TSTRING "Defining a t1 range..."
RDSTART1 TSTRING "a"
RFROM1 TNUMBER 5
RTO1 TNUMBER 10
RDEND1 TVOID 0V
PRINTLN TSTRING "Implementing a t1 range..."
RSTART1 TSTRING "a"
RANGE1 TNUMBER 6
REND1 TSTRING "a"
PRINTLN TSTRING "Testing load and store..."
PRINT TSTRING "a: "
RLOAD1 TSTRING "a"
PRINTLN TVOID 0V
ALOAD TNUMBER 10
RSTORE1 TSTRING "a"
PRINT TSTRING "a: "
RLOAD1 TSTRING "a"
PRINTLN TVOID 0V
PRINTLN TSTRING "Quitting..."
QUIT TVOID 0


END TVOID 0V