VERSION TVOID 0V


PRINTLN TSTRING "Defining a t2 range..."
RDSTART2 TSTRING "a"
RFROM2 TNUMBER 4
RTO2 TNUMBER 10
RDEND2 TVOID 0V
PRINTLN TSTRING "Implementing a t2 range..."
RSTART2 TSTRING "a"
RANGE2 TSTRING "a"
PRINTLN TSTRING "Testing load..."
RPREP2 TSTRING "a"
RLOAD2 TNUMBER 5
PRINT TSTRING "a: "
PRINTLN TVOID 0V
PRINTLN TSTRING "Quitting..."
QUIT TVOID 0


END TVOID 0V