#line 2 "pnfha.cpp"

#line 4 "pnfha.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 162
#define YY_END_OF_BUFFER 163
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[687] =
    {   0,
      119,  119,  163,  161,  159,  159,   23,  161,   36,   15,
       21,  161,    8,    9,   13,   11,    7,   12,   33,   14,
        3,    3,   24,    6,   28,   10,   29,   32,  119,   34,
       35,   16,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  157,  161,  158,  159,   27,   17,    0,
        5,  119,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   20,    0,   18,   19,  160,
        3,    3,    1,   30,   26,   31,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,   65,  115,  113,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,   46,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,   22,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    4,  160,    3,  119,
      119,  119,  119,  115,  119,  119,   43,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  101,  119,   42,
      119,  119,  110,  110,  119,  119,  119,  119,  119,   79,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      115,  109,   48,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  106,  119,  119,  110,  119,  119,  119,
      119,  119,  119,   37,  119,  112,  119,  119,  119,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  139,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  119,  119,  119,  119,  119,  119,
       50,  119,  119,  119,  119,  119,   67,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,   66,  119,   93,  119,  119,  119,  119,   88,  119,
      119,  119,  119,  119,  119,   80,  119,   45,   55,  119,
      119,  119,  119,  119,  119,   44,   92,  119,   56,  119,
      109,  119,  119,  119,  119,  119,   47,  119,  118,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  102,    2,
      119,  112,  119,  119,  119,  119,  105,  119,  107,  156,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  139,  120,  122,    0,    0,
        0,    0,    0,    0,    0,    0,  108,    0,  131,    0,
      127,    0,    0,    0,    0,    0,    0,   75,  119,  119,
      119,   97,  119,  119,   98,  119,   71,   68,  119,  119,
       83,  119,  119,  119,   53,  119,  119,  119,   78,  119,
      119,  103,   94,  119,   60,  119,   85,   86,  119,  119,
       91,  119,   58,  119,  114,  119,   72,  119,  119,  119,
      119,  119,  119,  119,  119,   38,   95,  119,  119,  119,
      119,   64,  119,  119,  119,  119,  119,  119,  119,  116,

      119,   73,  156,    0,    0,    0,    0,    0,    0,    0,
      148,    0,  144,    0,    0,    0,    0,    0,    0,  121,
        0,    0,    0,    0,    0,    0,    0,    0,  132,  129,
        0,    0,    0,  126,  128,  119,  111,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  104,  119,   40,
       87,  119,  119,   89,  119,  100,  119,  109,  119,  119,
       96,  119,  119,   57,  117,   76,  119,   51,  119,   49,
      119,  119,  119,    0,    0,    0,    0,    0,    0,    0,
      149,  146,    0,    0,    0,  143,  145,    0,    0,    0,
        0,    0,    0,    0,  125,  130,    0,    0,  119,  119,

      119,  119,   84,  119,  119,   52,  119,   69,   77,  119,
       81,  119,  119,  119,   99,  119,   39,  119,  119,  119,
      119,  119,   54,    0,    0,    0,    0,    0,    0,  142,
      147,    0,    0,    0,    0,  133,  136,  135,  134,    0,
      124,    0,  119,  119,   70,  119,  119,   82,  119,   41,
       90,  119,   62,  119,  119,  119,    0,    0,  150,  153,
      152,  151,  141,    0,  137,  138,    0,  123,   74,  119,
      119,  119,  119,  119,  154,  155,  140,    0,  119,  119,
       63,   59,   61,    0,  112,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   35,   36,   35,   35,   37,   38,   39,   35,   40,
       35,   35,   35,   41,   35,   42,   35,   35,   35,   35,
       43,    1,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   35,   56,   57,   58,   59,
       60,   61,   35,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   71,   72,   73,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[693] =
    {   0,
        0,    0,  768,  769,   72,   75,   54,  761,    0,   92,
      757,    0,  769,  769,  769,  751,  769,  748,  769,  745,
       64,   70,  769,  769,  736,  735,  734,  769,    0,  769,
      769,  769,   46,   56,   86,   54,   95,  111,  699,   47,
       68,  144,   44,  115,  693,   66,  123,  114,  131,  698,
      137,  702,  704,  769,  682,  769,  199,  769,  769,  747,
      769,    0,  166,  747,  715,  714,  719,  174,  699,  700,
      695,   64,  131,  698,  685,  769,  733,  769,  769,    0,
      206,  213,    0,  769,  769,  769,  692,  675,   41,  679,
       62,  681,   93,  691,  678,  689,  675,  683,  670,  685,

      680,   83,  140,  683,  662,  666,  675,  155,  665,  662,
      144,  662,  672,  671,  664,  663,  659,  658,  157,  655,
       94,  669,  173,  658,  648,  653,    0,  182,    0,  664,
      652,  663,  651,  658,  654,  644,  647,  640,  651,  177,
      647,  638,  641,  194,  630,  647,  188,  649,  641,  636,
      643,  628,  631,  629,  628,  151,  634,  633,  625,  769,
      681,  220,  634,  196,  207,  637,  624,  678,  642,  650,
      643,  228,  649,  641,  640,  639,  625,  616,  620,  608,
      620,  212,  608,  619,  618,  616,  769,    0,  253,  202,
      614,  616,  616,    0,  133,  615,    0,  612,  598,  612,

      599,  600,  609,  604,  591,  601,  590,  602,  592,  199,
      586,  593,  585,  599,  585,  593,  589,    0,  591,  586,
      582,  584,  579,    0,  574,  576,  583,  584,  582,  581,
      576,  583,  574,  566,  562,  566,  561,  573,  558,  564,
      556,  556,  568,  565,  567,  182,  552,  568,  556,  565,
      551,  564,    0,  555,  550,  554,  554,  556,  550,  553,
      538,  541,  535,    0,  538,  544,  536,  533,  546,  536,
      108,  543,  542,  537,  526,  527,  539,  531,  527,  582,
      235,  556,  548,  547,  546,  529,  517,  529,  218,  517,
      528,  527,  525,    0,  566,  565,  533,  542,  534,  528,

      531,  528,  528,  500,  515,  508,  511,  223,  510,  510,
      499,  501,  495,  505,  489,  503,  494,  501,  501,  481,
        0,  494,  486,  491,  495,  489,    0,  493,  496,  495,
      485,  489,  484,  483,  483,  472,  484,  469,  471,  477,
      476,    0,  478,  463,  469,  463,  475,  462,    0,  473,
      464,  456,  462,  470,  460,    0,  470,    0,    0,  458,
      465,  451,  452,  456,  448,    0,    0,  449,    0,  446,
      462,  457,  442,  443,  441,  440,    0,  452,    0,  439,
      448,  438,  448,  447,  446,  437,  435,  445,    0,    0,
      444,  224,  439,  444,  432,  434,    0,  437,    0,    0,

      458,  450,  444,  447,  444,  444,  426,  429,  224,  428,
      428,  417,  419,  413,  423,    0,  769,  769,  465,  431,
      433,  437,  436,  435,  434,  408,  769,  406,  769,  412,
      769,  411,  411,  399,  395,  399,  406,    0,  394,  392,
      398,    0,  407,  384,    0,  405,    0,    0,  386,  401,
        0,  390,  384,  388,    0,  397,  386,  387,    0,  391,
      385,    0,    0,  377,    0,  389,    0,    0,  388,  374,
        0,  373,    0,  372,    0,  370,    0,  380,  364,  377,
      374,  368,  365,  370,  372,  369,  359,  360,  368,  363,
      265,  374,  367,  354,  364,  357,  364,  360,  366,    0,

      353,    0,    0,  371,  373,  377,  376,  375,  374,  347,
      769,  353,  769,  352,  352,  340,  336,  340,  347,  769,
      365,  364,  385,  384,  383,  382,  327,  340,  769,  769,
      338,  325,  338,  769,  769,  324,    0,  338,  326,  327,
      319,  318,  326,  315,  325,  314,  313,    0,  325,  318,
        0,  312,  316,    0,  323,    0,  305,  304,  303,  309,
        0,  316,  303,    0,    0,    0,  301,    0,  312,    0,
      300,  305,  302,  327,  326,  347,  346,  345,  344,  303,
      769,  769,  301,  288,  301,  769,  769,  339,  338,  336,
      335,  334,  333,  287,  769,  769,  339,  291,  281,  283,

      275,  287,    0,  277,  285,    0,  289,    0,    0,  275,
        0,  274,  268,  280,    0,  279,    0,  267,  264,  272,
      262,  274,    0,  313,  312,  310,  309,  308,  307,  769,
      769,  314,  266,  304,  303,  769,  769,  769,  769,  267,
      769,  309,  260,  260,    0,  248,  250,    0,  242,    0,
        0,  252,    0,  255,  246,  253,  291,  290,  769,  769,
      769,  769,  769,  296,  769,  769,  233,  769,    0,  243,
      231,  226,  232,  218,  769,  769,  769,  160,  124,   78,
        0,    0,    0,   31,    0,  769,  286,   79,  289,  292,
      295,  298

    } ;

static yyconst flex_int16_t yy_def[693] =
    {   0,
      686,    1,  686,  686,  686,  686,  686,  687,  688,  686,
      686,  689,  686,  686,  686,  686,  686,  686,  686,  686,
      688,  688,  686,  686,  686,  686,  686,  686,  688,  686,
      686,  686,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  686,  686,  686,  686,  686,  686,  687,
      686,  688,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  690,
      686,  688,  688,  686,  686,  686,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  690,  686,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  691,  686,  686,  686,  686,  686,  686,

      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  692,

      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  691,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,

      688,  688,  692,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  688,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  688,  688,
      688,  688,  688,  688,  686,  686,  686,  686,  688,  688,
      688,  688,  688,  686,  688,    0,  686,  686,  686,  686,
      686,  686

    } ;

static yyconst flex_int16_t yy_nxt[843] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   23,   24,   25,   26,   27,   28,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   30,   31,   32,   29,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   29,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   29,   29,   53,
       54,   55,   56,   57,   57,   57,   57,   57,   57,   58,
       81,   62,   82,   82,   82,   82,   81,  192,   82,   82,
       82,   82,  427,  124,  133,   87,   88,  125,   59,   63,

      193,   64,   89,  134,  107,   83,   90,   91,   92,   93,
       95,   94,   96,  108,  195,   97,  126,   98,  109,  127,
      180,   65,  181,  196,  139,  140,  128,  141,   66,  207,
      142,   67,   99,  208,  100,  101,  685,   68,   69,  102,
       70,   71,   72,  194,  232,  103,   73,  104,  105,   74,
      106,  110,  198,  111,  233,  112,   75,  115,  390,  116,
      113,  117,  114,  129,  129,  135,  391,  146,  118,  143,
      119,  120,  121,  144,  136,  161,  122,  147,  148,  137,
      149,  150,  182,  155,  151,  685,  145,  156,  183,  184,
      130,  264,  152,  220,  131,  264,  157,  209,  210,  153,

       57,   57,   57,  132,  172,  173,  215,  174,  221,  275,
      175,  162,  276,  216,  176,  163,  164,  229,  230,  684,
      165,  217,  315,  166,  189,  189,  189,  189,  240,   81,
      167,   82,   82,   82,   82,  235,  236,  253,  367,  254,
      258,  368,  241,  264,  242,  224,  259,  265,  333,  266,
      281,  282,  287,  283,  288,  260,  284,  261,  289,  298,
      285,  309,  334,  316,  290,  291,  401,  410,  299,  496,
      310,  189,  189,  189,  189,  402,  411,  430,  512,  683,
      431,  513,  682,  497,  565,  565,   60,  681,   60,   77,
      680,   77,  188,  679,  188,  416,  678,  416,  503,  677,

      503,  676,  675,  674,  673,  672,  671,  670,  399,  397,
      537,  669,  668,  667,  666,  665,  664,  663,  662,  661,
      660,  659,  658,  657,  264,  656,  655,  654,  653,  399,
      399,  652,  651,  650,  649,  648,  647,  646,  645,  644,
      643,  642,  641,  640,  639,  638,  637,  636,  635,  634,
      633,  632,  631,  630,  629,  628,  627,  626,  625,  624,
      623,  622,  621,  264,  620,  619,  618,  617,  616,  615,
      614,  613,  612,  611,  610,  609,  608,  607,  606,  605,
      604,  603,  602,  601,  397,  600,  599,  598,  597,  596,
      595,  594,  593,  592,  591,  590,  589,  588,  587,  586,

      585,  584,  583,  582,  581,  580,  579,  578,  577,  576,
      575,  574,  573,  572,  571,  570,  569,  568,  567,  397,
      566,  564,  563,  562,  561,  560,  559,  558,  475,  397,
      399,  557,  264,  556,  555,  264,  554,  553,  552,  551,
      550,  549,  548,  547,  546,  545,  544,  543,  542,  541,
      540,  539,  194,  538,  537,  537,  536,  535,  534,  533,
      532,  531,  530,  529,  528,  527,  526,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  511,
      510,  509,  508,  507,  506,  505,  504,  502,  501,  500,
      499,  498,  194,  495,  494,  493,  492,  224,  491,  490,

      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  264,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  390,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  455,  454,  453,  452,
      451,  450,  449,  448,  447,  446,  445,  444,  443,  442,
      264,  441,  440,  439,  438,  437,  436,  435,  434,  433,
      432,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  415,  414,  413,  412,  409,  408,
      407,  406,  405,  404,  403,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  389,  264,  388,  387,  386,  385,

      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  366,  365,  364,  363,
      362,  361,  360,  224,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  314,  313,  312,  311,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  297,  296,
      295,  294,  293,  292,  286,  280,  279,  278,  277,  274,
      273,  272,  271,  270,  269,  268,  267,  263,  262,  257,

      256,  255,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  239,  238,  237,  234,  231,  228,  227,  226,
      225,  224,  223,  222,  219,  218,  214,  213,  212,  211,
      206,  205,  204,  203,  202,  201,  200,  199,  197,  194,
      191,  190,  187,  186,  185,  179,  178,  177,  171,  170,
      169,  168,   61,  160,  159,  158,  154,  138,  123,   86,
       85,   84,   80,   79,   78,   76,   61,  686,    3,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,

      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686
    } ;

static yyconst flex_int16_t yy_chk[843] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    6,    6,    6,    7,
       21,  688,   21,   21,   21,   21,   22,   89,   22,   22,
       22,   22,  684,   40,   43,   33,   33,   40,    7,   10,

       89,   10,   33,   43,   36,   21,   33,   33,   33,   33,
       34,   33,   34,   36,   91,   34,   41,   34,   36,   41,
       72,   10,   72,   91,   46,   46,   41,   46,   10,  102,
       46,   10,   35,  102,   35,   35,  680,   10,   10,   35,
       10,   10,   10,   93,  121,   35,   10,   35,   35,   10,
       35,   37,   93,   37,  121,   37,   10,   38,  271,   38,
       37,   38,   37,   42,   42,   44,  271,   48,   38,   47,
       38,   38,   38,   47,   44,   63,   38,   48,   48,   44,
       48,   49,   73,   51,   49,  679,   47,   51,   73,   73,
       42,  195,   49,  111,   42,  195,   51,  103,  103,   49,

       57,   57,   57,   42,   68,   68,  108,   68,  111,  156,
       68,   63,  156,  108,   68,   63,   63,  119,  119,  678,
       63,  108,  190,   63,   81,   81,   81,   81,  128,   82,
       63,   82,   82,   82,   82,  123,  123,  140,  246,  140,
      144,  246,  128,  147,  128,  128,  144,  147,  210,  147,
      162,  162,  164,  162,  164,  144,  162,  144,  165,  172,
      162,  182,  210,  190,  165,  165,  281,  289,  172,  392,
      182,  189,  189,  189,  189,  281,  289,  308,  409,  674,
      308,  409,  673,  392,  491,  491,  687,  672,  687,  689,
      671,  689,  690,  670,  690,  691,  667,  691,  692,  664,

      692,  658,  657,  656,  655,  654,  652,  649,  647,  646,
      644,  643,  642,  640,  635,  634,  633,  632,  629,  628,
      627,  626,  625,  624,  622,  621,  620,  619,  618,  616,
      614,  613,  612,  610,  607,  605,  604,  602,  601,  600,
      599,  598,  597,  594,  593,  592,  591,  590,  589,  588,
      585,  584,  583,  580,  579,  578,  577,  576,  575,  574,
      573,  572,  571,  569,  567,  563,  562,  560,  559,  558,
      557,  555,  553,  552,  550,  549,  547,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  536,  533,  532,  531,
      528,  527,  526,  525,  524,  523,  522,  521,  519,  518,

      517,  516,  515,  514,  512,  510,  509,  508,  507,  506,
      505,  504,  501,  499,  498,  497,  496,  495,  494,  493,
      492,  490,  489,  488,  487,  486,  485,  484,  483,  482,
      481,  480,  479,  478,  476,  474,  472,  470,  469,  466,
      464,  461,  460,  458,  457,  456,  454,  453,  452,  450,
      449,  446,  444,  443,  441,  440,  439,  437,  436,  435,
      434,  433,  432,  430,  428,  426,  425,  424,  423,  422,
      421,  420,  419,  415,  414,  413,  412,  411,  410,  408,
      407,  406,  405,  404,  403,  402,  401,  398,  396,  395,
      394,  393,  391,  388,  387,  386,  385,  384,  383,  382,

      381,  380,  378,  376,  375,  374,  373,  372,  371,  370,
      368,  365,  364,  363,  362,  361,  360,  357,  355,  354,
      353,  352,  351,  350,  348,  347,  346,  345,  344,  343,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  326,  325,  324,  323,  322,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  293,  292,  291,  290,  288,  287,
      286,  285,  284,  283,  282,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  270,  269,  268,  267,  266,  265,

      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      252,  251,  250,  249,  248,  247,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  223,  222,  221,
      220,  219,  217,  216,  215,  214,  213,  212,  211,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  196,  193,  192,  191,  186,  185,  184,  183,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  171,  170,
      169,  168,  167,  166,  163,  161,  159,  158,  157,  155,
      154,  153,  152,  151,  150,  149,  148,  146,  145,  143,

      142,  141,  139,  138,  137,  136,  135,  134,  133,  132,
      131,  130,  126,  125,  124,  122,  120,  118,  117,  116,
      115,  114,  113,  112,  110,  109,  107,  106,  105,  104,
      101,  100,   99,   98,   97,   96,   95,   94,   92,   90,
       88,   87,   77,   75,   74,   71,   70,   69,   67,   66,
       65,   64,   60,   55,   53,   52,   50,   45,   39,   27,
       26,   25,   20,   18,   16,   11,    8,    3,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,

      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  686,  686,  686,  686,  686,
      686,  686
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[163] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pnfha.lpp"
#line 5 "pnfha.lpp"
/* Prologue */
#include <stdarg.h>

#include "pnfha.tab.cpp"


void generate_code();
void generate_pcode(bool names);
void generate_switch_code();
String strip_quotes(String str);
void generate_comment_code();


PNF_Variable lval;
/* Flex Definitions */
/* Flex Patterns Below %% */
#line 910 "pnfha.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 362 "pnfha.lpp"


#line 1095 "pnfha.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 687 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 769 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 364 "pnfha.lpp"
lval.put("1"); yylval = lval; return VOIDV;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 366 "pnfha.lpp"
{
			 String b;
			 if (strcmp(yytext, "true") == 0)
		          b = "true";
			 else if (strcmp(yytext, "false") == 0)
			  b = "false";
			 else
 			  b = "true";

			 lval.put(b); 
			 yylval = lval.to_boolean(); 
			 return BOOLEANV;
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 380 "pnfha.lpp"
{
			 double d = atof(yytext);
			 PNF_Number n(d);
			 PNF_Variable v(n);
			 lval.put(v.to_number());
			 yylval.put(lval.to_number());
			 return NUMBERV;
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 389 "pnfha.lpp"
{
			 char ch = yytext[1];
			 PNF_Character c(ch);
			 lval.put(c);
			 yylval = lval.to_character();
			 return CHARACTERV;
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 397 "pnfha.lpp"
{
			 String str = yytext;
			 PNF_String s(str);
			 lval.put(s);
			 yylval = lval.to_string();
			 return STRINGV;
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 405 "pnfha.lpp"
lval.put("1"); yylval = lval; return SEND;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 407 "pnfha.lpp"
lval.put("1"); yylval = lval; return COMMA;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 409 "pnfha.lpp"
lval.put("0"); yylval = lval; return LEFTP;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 411 "pnfha.lpp"
lval.put("0"); yylval = lval; return RIGHTP;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 413 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPEQUAL;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 415 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPPLUS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 417 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPMINUS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 419 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPTIMES;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 421 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPDIV;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 423 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPMODULUS;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 425 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPPOWER;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 427 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPROOT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 429 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPINC;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 431 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPDEC;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 433 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPAND;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 435 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPAMP;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 437 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPOR;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 439 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPNOT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 441 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPCOLON;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 443 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPSUB;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 445 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPEQU;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 447 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPNEQU;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 449 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPLSS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 451 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPGTR;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 453 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPLEQU;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 455 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPGEQU;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 457 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPQUES;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 459 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPDOT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 461 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPLSQ;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 463 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPRSQ;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 465 "pnfha.lpp"
lval.put("0"); yylval = lval; return OPSTR;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 467 "pnfha.lpp"
lval.put("0"); yylval = lval; return VAR;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 469 "pnfha.lpp"
lval.put("0"); yylval = lval; return PRINT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 471 "pnfha.lpp"
lval.put("0"); yylval = lval; return PRINTLN;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 473 "pnfha.lpp"
lval.put("0"); yylval = lval; return EPRINT;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 475 "pnfha.lpp"
lval.put("0"); yylval = lval; return EPRINTLN;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 477 "pnfha.lpp"
lval.put("0"); yylval = lval; return END;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 479 "pnfha.lpp"
lval.put("0"); yylval = lval; return ASM;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 481 "pnfha.lpp"
lval.put("0"); yylval = lval; return LOAD;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 483 "pnfha.lpp"
lval.put("0"); yylval = lval; return GOTO;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 485 "pnfha.lpp"
lval.put("0"); yylval = lval; return ST;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 487 "pnfha.lpp"
lval.put("0"); yylval = lval; return PUSH;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 489 "pnfha.lpp"
lval.put("0"); yylval = lval; return POP;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 491 "pnfha.lpp"
lval.put("0"); yylval = lval; return TYPEOF;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 493 "pnfha.lpp"
lval.put("0"); yylval = lval; return ATOC;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 495 "pnfha.lpp"
lval.put("0"); yylval = lval; return SWITCH;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 497 "pnfha.lpp"
lval.put("0"); yylval = lval; return CSWITCH;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 499 "pnfha.lpp"
lval.put("0"); yylval = lval; return CRASH;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 501 "pnfha.lpp"
lval.put("0"); yylval = lval; return VERSION;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 503 "pnfha.lpp"
lval.put("0"); yylval = lval; return HALT;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 505 "pnfha.lpp"
lval.put("0"); yylval = lval; return MODT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 507 "pnfha.lpp"
lval.put("0"); yylval = lval; return RETURN;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 509 "pnfha.lpp"
lval.put("0"); yylval = lval; return GOSUB;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 511 "pnfha.lpp"
lval.put("0"); yylval = lval; return SUB;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 513 "pnfha.lpp"
lval.put("0"); yylval = lval; return EVENT;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 515 "pnfha.lpp"
lval.put("0"); yylval = lval; return UNREGISTER;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 517 "pnfha.lpp"
lval.put("0"); yylval = lval; return REGISTER;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 519 "pnfha.lpp"
lval.put("0"); yylval = lval; return REREGISTER;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 521 "pnfha.lpp"
lval.put("0"); yylval = lval; return STORE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 523 "pnfha.lpp"
lval.put("0"); yylval = lval; return IF;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 525 "pnfha.lpp"
{
			 lval.put("0");
			 yylval = lval;
			 return ELSE;
			}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 531 "pnfha.lpp"
lval.put("0"); yylval = lval; return CASE;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 533 "pnfha.lpp"
lval.put("0"); yylval = lval; return CCASE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 535 "pnfha.lpp"
lval.put("0"); yylval = lval; return DEFAULT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 537 "pnfha.lpp"
lval.put("0"); yylval = lval; return CDEFAULT;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 539 "pnfha.lpp"
lval.put("0"); yylval = lval; return BREAK;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 541 "pnfha.lpp"
lval.put("0"); yylval = lval; return LABEL;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 543 "pnfha.lpp"
lval.put("0"); yylval = lval; return WHILE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 545 "pnfha.lpp"
lval.put("0"); yylval = lval; return ADDRESSOF;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 547 "pnfha.lpp"
lval.put("0"); yylval = lval; return ADD2V;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 549 "pnfha.lpp"
lval.put("0"); yylval = lval; return STOREA;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 551 "pnfha.lpp"
lval.put("0"); yylval = lval; loopexpr = true; return DOWHILE;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 553 "pnfha.lpp"
lval.put("0"); yylval = lval; loopexpr = true; return DOFOR;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 555 "pnfha.lpp"
lval.put("0"); yylval = lval; return FOR;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 557 "pnfha.lpp"
lval.put("0"); yylval = lval; return FVAR;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 559 "pnfha.lpp"
lval.put("0"); yylval = lval; inforever = true; return FOREVER;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 561 "pnfha.lpp"
lval.put("0"); yylval = lval; return CONTINUE;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 563 "pnfha.lpp"
lval.put("0"); yylval = lval; return CHECK;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 565 "pnfha.lpp"
lval.put("0"); yylval = lval; return HCMNT;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 567 "pnfha.lpp"
lval.put("0"); yylval = lval; return FMODE;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 569 "pnfha.lpp"
lval.put("0"); yylval = lval; return FOPEN;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 571 "pnfha.lpp"
lval.put("0"); yylval = lval; return FCLOSE;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 573 "pnfha.lpp"
lval.put("0"); yylval = lval; return FEOF;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 575 "pnfha.lpp"
lval.put("0"); yylval = lval; return FPRINT;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 577 "pnfha.lpp"
lval.put("0"); yylval = lval; return FPRINTLN;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 579 "pnfha.lpp"
lval.put("0"); yylval = lval; return FREAD;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 581 "pnfha.lpp"
lval.put("0"); yylval = lval; return MEML;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 583 "pnfha.lpp"
lval.put("0"); yylval = lval; return ENUM;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 585 "pnfha.lpp"
lval.put("0"); yylval = lval; return ENUMV;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 587 "pnfha.lpp"
lval.put("0"); yylval = lval; return RANGE;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 589 "pnfha.lpp"
lval.put("0"); yylval = lval; return RANGEV;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 591 "pnfha.lpp"
lval.put("0"); yylval = lval; return ARRAY;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 593 "pnfha.lpp"
lval.put("0"); yylval = lval; return BLANK;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 595 "pnfha.lpp"
lval.put("0"); yylval = lval; return PNFASM;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 597 "pnfha.lpp"
lval.put("0"); yylval = lval; return LENGTH;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 599 "pnfha.lpp"
lval.put("0"); yylval = lval; return DUP;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 601 "pnfha.lpp"
lval.put("0"); yylval = lval; return THEN;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 603 "pnfha.lpp"
lval.put("0"); yylval = lval; return ENDIF;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 605 "pnfha.lpp"
lval.put("0"); yylval = lval; return DONEIF;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 607 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return TYPE;
			}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 614 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return LTYPE;
			}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 621 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return GTYPE;
			}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 628 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return RTYPE;
			}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 635 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return VTYPE;
			}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 642 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return STYPE;
			}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 649 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return ATYPE;
			}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 656 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return CTYPE;
			}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 663 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return CMTYPE;
			}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 670 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return BFMODEC;
			}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 677 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return FMODEC;
			}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 684 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return VTYPE2;
			}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 691 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return RTYPE2;
			}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 698 "pnfha.lpp"
lval.put("0"); yylval = lval; return READ;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 700 "pnfha.lpp"
{
			 String str = yytext;
			 lval.put(str);
			 yylval.put(lval.to_string());
			 return ID;
			}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 707 "pnfha.lpp"
return PBIN;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 709 "pnfha.lpp"
return PPBIN;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 711 "pnfha.lpp"
return PLIB;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 713 "pnfha.lpp"
return PINCLUDE;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 715 "pnfha.lpp"
return PIMPORT;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 717 "pnfha.lpp"
return PDEFINE;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 719 "pnfha.lpp"
return PMACRO;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 721 "pnfha.lpp"
return PENDM;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 723 "pnfha.lpp"
return PUNDEF;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 725 "pnfha.lpp"
return PIFDEF;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 727 "pnfha.lpp"
return PIFNDEF;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 729 "pnfha.lpp"
return PELSE;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 731 "pnfha.lpp"
return PENDIF;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 733 "pnfha.lpp"
return PPDATE;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 735 "pnfha.lpp"
return PPTIME;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 737 "pnfha.lpp"
return PPLINE;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 739 "pnfha.lpp"
return PPFILE;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 741 "pnfha.lpp"
return PPCDATE;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 743 "pnfha.lpp"
return PPCTIME;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 745 "pnfha.lpp"
{ 
		 ASTNode pp_statement("pp_statement");
		 pp_statement.conprint("' %s\n", yytext); 
		 tree.add_node(pp_statement); 
		}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 751 "pnfha.lpp"
return PPINCLUDE;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 753 "pnfha.lpp"
return PPIMPORT;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 755 "pnfha.lpp"
return PPDEFINE;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 757 "pnfha.lpp"
return PPMACRO;
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 759 "pnfha.lpp"
return PPENDM;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 761 "pnfha.lpp"
return PPUNDEF;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 763 "pnfha.lpp"
return PPIFDEF;
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 765 "pnfha.lpp"
return PPIFNDEF;
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 767 "pnfha.lpp"
return PPELSE;
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 769 "pnfha.lpp"
return PPENDIF;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 771 "pnfha.lpp"
return PPPDATE;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 773 "pnfha.lpp"
return PPPTIME;
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 775 "pnfha.lpp"
return PPPLINE;
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 777 "pnfha.lpp"
return PPPFILE;
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 779 "pnfha.lpp"
return PPPCDATE;
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 781 "pnfha.lpp"
return PPPCTIME;
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 783 "pnfha.lpp"
{ 
		 ASTNode pp_statement("pp_statement");
		 pp_statement.conprint("'! %s\n", yytext); 
		 tree.add_node(pp_statement);
		}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 789 "pnfha.lpp"
{
			 inblock = true;
			 blockinstmt = true;
			 if ((!loopexpr || midloop != 0) && !inloop && !infor && !inforever && !intop && !inif)
			 {
			  ++scope;
			  varTable.insert();
			  varTable[scope].insert();
			  ++midloop;
			 }

			 lval.put("0");
			 yylval = lval;
			 return LEFTB;
			}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 805 "pnfha.lpp"
{
			 if ((!loopexpr || midloop != 0) && !inloop && !infor && !inforever && !intop && !inif)
			 {
			  --scope;
			  varTable.remove();
			  --midloop;
			 }
			 else
			 {
			  if (infor)
			  {
			   --inforfor;
			   if (inforfor == 0)
			    infor = false;
			  }

			  if (loopexpr)
			   inloop = true;
			  else
			   inloop = false;

			  loopexpr = false;
			  inforever = false;

			  if (intop)
			  {
			   --intopfor;
			   if (intopfor == 0)
			    intop = false;
			  }
			 }

			 lval.put("0");
			 yylval = lval;
			 inblock = false;
			
			 return RIGHTB;
			}
	YY_BREAK
case 159:
/* rule 159 can match eol */
YY_RULE_SETUP
#line 844 "pnfha.lpp"
/* Eat up Whitespace */
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 846 "pnfha.lpp"
/* Eat up comment */
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 848 "pnfha.lpp"
{
			 String str = "Scan error: ";
			 str += yytext;
			 yyerror(str.getString().c_str());

			 lval.put("0");
			 yylval = lval;
			}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 857 "pnfha.lpp"
ECHO;
	YY_BREAK
#line 2170 "pnfha.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 687 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 687 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 686);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 857 "pnfha.lpp"


/* Additional Code */
int main(int argc, char ** argv)
{
 yydebug = 0;


 varTable[scope].insert();


 if (argc == 3)
 {
  String extension = get_extension(argv[1]);
  if (extension == ".pppha")
   preprocess(argv[1]);

  FILE * input = fopen((strip_extension(argv[1]) + ".pha").getString().c_str(), "r");
  if (!input)
  {
   yyerror("can't open file");
   return -1;
  }
  yyin = input;
  output = fopen(argv[2], "w");
  if (!output)
  {
   yyerror("can't open file for write");
   return -1;
  }
  fprintf(output, "VERSION TVOID 0V\n\n\n");

  
  int ret = yyparse();
  //generate_pcode(false);
  //generate_switch_code();
  //generate_comment_code();
  generate_code();


  fprintf(output, "\n\nEND TVOID 0V");
  fclose(output);
  return ret;
 }
 else
  yyerror("can't find input file or output file.");
}

void yyerror(char const * c)
{
 cout << "* ERROR: " << yylineno << ": " << c << endl;
}

String get_extension(String fileName)
{
 unsigned long index = fileName.getString().find(".");
 if (index == string::npos)
  yyerror((char *)"File has No Extension.");

 String extension = fileName.getString().substr(index);


 return extension;
}

String strip_extension(String fileName)
{
 unsigned long index = fileName.getString().find(".");
 if (index == string::npos)
  yyerror((char *)"File has No Extension.");

 String stripped = fileName.getString().substr(0, index);


 return stripped;
}

void preprocess(String arg)
{ 
 String cmd = (String)"./pnfpp" + (strip_extension(arg) + (char *)".pppha") + 
 	      (strip_extension(arg) + (char *)".pha");
 system(cmd.getString().c_str());
}

int conprint(const char * format, ...)
{
 va_list arg;
 int done = 0;

 va_start(arg, format);

 out.insert();
 done = vsnprintf(outbuffer, 256, format, arg);
 String str = "";
 if (outbuffer != NULL)
  str += outbuffer;
 out[outcount] = str;
 ++outcount;

 va_end(arg);


 return done;
}

void generate_code()
{
 unsigned long len = out.length();
 for (unsigned long i = 0; i < out.length(); ++i)
 {
  if (out[i].getString() == "")
   out.remove(i);
 }

 for (unsigned long i = 0; i < out.length(); ++i)
 {
  fprintf(output, "%s", out[i].getString().c_str());
 }
}

void movelineno(unsigned long index, unsigned long line)
{
 unsigned long i;
 for (i = 0; i < out.length(); ++i)
 {
  if (i < statementlineno.length())
   if (statementlineno[i] == line)
    break;
 }
 cout << i << endl;
 //out.move(index, i);
}

void sort(Array<unsigned long> & array)
{
 bool changed = false;
 do
 {
  changed = false;
  for (unsigned long i = 0; (i + 1) < array.length(); ++i)
  {
   if (array[i + 1] < array[i])
   {
    swap(array[i], array[i + 1]);
    changed = true;
   }
  }
 } while (changed == true);
}

void sort_lines(Array<String> & array)
{
 bool changed = false;
 do
 {
  changed = false;
  for (unsigned long i = 0; (i + 1) < array.length(); ++i)
  {
   String str;
   str = array[i];
   unsigned long k = str.getString().find(':');
   if (k == string::npos)
   {
    continue;
   }
   str = array[i].getString().substr(k + 2);
   unsigned long l = atoi(str.getString().c_str());

   str = array[i + 1];
   k = str.getString().find(':');
   if (k == string::npos)
   {
    continue;
   }
   str = array[i + 1].getString().substr(k + 2);
   unsigned long l2 = atoi(str.getString().c_str());

   if (l2 < l)
   {
    String temp1 = array[i], temp2 = array[i + 1];
    array[i] = temp2;
    array[i + 1] = temp1;

    changed = true;
   }
  }
 } while (changed == true);
}

void generate_pcode(bool names)
{
 unsigned long len = tree.nodenumber();

 for (unsigned long i = 0; i < len; ++i)
 {
  ASTNode node(tree.getNode(i));
  String nodename = node.getName();
  nodename += ":\n\n";
  if (names)
   conprint("%s", nodename.getString().c_str());

  for (unsigned long j = 0; j < node.getValue().length(); ++j)
   conprint("%s", node.getValue()[j].getString().c_str());
 }
}

void generate_switch_code()
{
 /*
  1. Determine if there is a switch or not. Do other steps only if there is a switch.
  2. Find highest switch_case.
  3. Replace the skip_switch_case that is higher than that with GOTOL TSTRING default_switch_(switchcount).
 */
 // Step 1
 if (switchfound)
 {
  // Step 2
  String num;
  String num2;
  String underscore = "_";
  String str;
  unsigned long j = 0;
  for (unsigned long i = 0; i < out.length(); ++i)
  {
   num.from_long(i);
   String line = out[i].getString();
   for (unsigned long k = 1; k <= switchcounter; ++k)
   {
    num2.from_long(k);
    str = (String)"LBL TSTRING \"switch_case_" + num2 + underscore + num + (String)"\"\n";
   
    for (unsigned long l = 0; l < out.length(); ++l)
    {
     if (out[l] == str)
      ++j;
    }
   }
  }

  // Step 3
  for (unsigned long i = 0; i < out.length(); ++i)
  {
   String line = out[i];
   num.from_long(j + 1);

   for (unsigned long k = 1; k <= switchcounter; ++k)
   {
    num2.from_long(k);
    str = (String)"GOTOL TSTRING \"skip_switch_case_" + num2 + underscore + num + (String)"\"\n";
   
    for (unsigned long l = 0; l < out.length(); ++l)
    {
     if (out[l] == str)
      j = l;
    }
   }
  }

  String num3;
  num3.from_long(switchcounter);
  Array<String> out2;
  for (unsigned long i = 0, k = 0; i < out.length(); ++i)
  {
   if (i != j)
   {
    out2[k] = out[i];
    ++k;
    out2.insert();
   }
   else
   {
    out2[k] = "GOTOL TSTRING \"default_switch_";
    out2[k] += num3;
    out2[k] += "\"\n";
    ++k;
    out2.insert();
   }
  }
  out = out2;
 }
}

String strip_quotes(String str)
{
 String str2 = "";

 for (unsigned long i = 0; i < str.length(); ++i)
 {
  if (i == 0)
   continue;
  else if (i == str.length() - 1)
   continue;
  else
   str2 += str[i];
 }

 return str2;
}

void generate_comment_code()
{
 for (unsigned long i = 0; i < out.length(); ++i)
 {
  if (out[i][0] == ';' && out[i][1] == '\\')
  {
   String str = "";
   for (unsigned long j = 0; j < out[i].length(); ++j)
   {
    if (j == 1)
     continue;
    else
     str += out[i][j];
   }
   out[i] = str;
  }
 }
}

