VERSION TVOID 0V


ALOAD TSTRING "Dennis"
VSTORE TVOID 0V
ALOAD TSTRING "Dennis"
ATOC TVOID 0V
ALOAD TCHARACTER a
EQU TVOID 0V
CGOTOL TSTRING "switch_case_1_1"
GOTOL TSTRING "default_switch_1"
PRINTLN TSTRING "Dennis"
ALOAD TCHARACTER b
EQU TVOID 0V
CGOTOL TSTRING "switch_case_1_2"
GOTOL TSTRING "default_switch_1"
PRINTLN TSTRING "Chris"
GOTOL TSTRING "default_switch_1"

END TVOID 0V