VERSION TVOID 0V


READ TNUMBER 0V
VSTORE TVOID 0V
READ TNUMBER 0V ; Read in A
VSTORE TVOID 0V
READ TNUMBER 0V ; Read in B
VSTORE TVOID 0V
VLOAD TNUMBER 1
VLOADC TNUMBER 1
MUL TVOID 0V
VSTORE TVOID 0V
VLOAD TNUMBER 2
VLOADC TNUMBER 2
MUL TVOID 0V
VLOADC TNUMBER 3
ADD TVOID 0V
VSTORE TVOID 0V
VLOAD TNUMBER 1
PRINT TVOID 0V
PRINT TCHARACTER ' '
VLOAD TNUMBER 2
PRINT TVOID 0V
PRINT TCHARACTER ' '
VLOAD TNUMBER 4
PRINT TVOID 0V
PRINT TCHARACTER ' '
PRINT TCHARACTER '\n'
ST TVOID 0V
CGOTO TVOID 9
QUIT TVOID 0


END TVOID 0V