VERSION TVOID 0V


PRINTLN TSTRING "Before subroutine..."
CALLL TVOID 0
PRINTLN TSTRING "After subroutine..."
QUIT TVOID 0


LBL TVOID 0V
PRINTLN TSTRING "In subroutine..."
RET TVOID 0V


END TVOID 0V