VERSION TVOID 0V


VAR TSTRING "a"
VAR TSTRING "b"
VAR TNUMBER 0


PRINTLN TSTRING "Defining an array..."
ASTART TSTRING "a"
AINDEX TVOID 0V
VAR TSTRING "a"
AINDEXE TVOID 0V

AINDEX TVOID 0V
VAR TSTRING "b"
AINDEXE TVOID 0V

AEND TVOID 0V


PRINTLN TSTRING "Testing load and store..."
PRINT TSTRING "a[1]: "
APREP TSTRING "a"
AIPREP TNUMBER 1
LOADIA TVOID 0V
PRINTLN TVOID 0V


PRINT TSTRING "Enter a string: "
READ TSTRING 0V
APREP TSTRING "a"
AIPREP TNUMBER 1
STOREIA TVOID 0V

PRINT TSTRING "Your string was: "
APREP TSTRING "a"
AIPREP TNUMBER 1
LOADIA TVOID 0V
PRINTLN TVOID 0V


PRINTLN TSTRING "Quitting..."
QUIT TVOID 0


END TVOID 0V