VERSION TVOID 0V


ALOAD TNUMBER 0
VSTORE TVOID 0V
ALOAD TNUMBER 0
VSTORE TVOID 0V
PRINT TSTRING "Loop until: "
READ TNUMBER 0V
VSTORE TVOID 0V
PRINTLN TSTRING ""
LBL TSTRING "do_while_body_1"
VADD TVOID 0
ADD2V TVOID 0V
PRINTLN TVOID 0V
VADD TVOID 0
ATOC TVOID 0V
VADD TVOID 0
ADD2V TVOID 0V
INC TVOID 0V
STOREA TVOID 0V
LBL TSTRING "do_while_test_1"
VADD TVOID 2
ADD2V TVOID 0V
ATOC TVOID 0V
VADD TVOID 0
ADD2V TVOID 0V
LSS TVOID 0V
CGOTOL TSTRING "do_while_body_1"
GOTOL TSTRING "do_while_end_1"
LBL TSTRING "do_while_end_1"
QUIT TVOID 0

END TVOID 0V