VERSION TVOID 0V


PRINTLN TSTRING "Before breakpoint."
EXADD TVOID 0
PRINTLN TSTRING "After breakpoint."
EXREM TVOID 0V
PRINTLN TSTRING "After breakpoint disabled."
QUIT TVOID 0
ELBL TVOID 0V
CALLL TVOID 0
RET TVOID 0V
LBL TVOID 0V
PRINTLN TSTRING "Hello World!"
RET TVOID 0V


END TVOID 0V