VERSION TVOID 0V


ALOAD TNUMBER 0
VSTORE TVOID 0V
PRINT TSTRING "Enter a number: "
READ TNUMBER 0V
ATOC TVOID 0V
VADD TVOID 0
SWITCH TVOID 0V
STOREA TVOID 0V
VLOAD TNUMBER 0
SWITCH2 TVOID 0V
SWBEGIN TVOID 0V
SWCASE TNUMBER 0
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Too small!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWCASE TNUMBER 5
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Good job!"
SWCEND TVOID 0V
SWCASE TNUMBER 4
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Nice pick!"
SWCEND TVOID 0V
SWCASE TNUMBER 3
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Excelent!"
SWCEND TVOID 0V
SWCASE TNUMBER 2
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Masterful!"
SWCEND TVOID 0V
SWCASE TNUMBER 1
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Incredible!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWDEFAULT TVOID 0V
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Too big!"
SWCEND TVOID 0V
SWEND TVOID 0V
QUIT TVOID 0


END TVOID 0V