VERSION TVOID 0V


ALOAD TNUMBER 0
VSTORE TVOID 0V
PRINT TSTRING "How many hellos?: "
READ TNUMBER 0V
ATOC TVOID 0V
VADD TVOID 0
SWITCH TVOID 0V
STOREA TVOID 0V
ATOC TVOID 0V
ALOAD TNUMBER 0
LBL TSTRING "forever_1"
SWITCH TVOID 0V
PUSH TVOID 0V
GTR TVOID 0V
CGOTOL TSTRING "top_iftrue_1"
GOTOL TSTRING "top_iffalse_1"
LBL TSTRING "top_iftrue_1"
VOID TVOID 0V
GOTOL TSTRING "top_end_1"
LBL TSTRING "top_iffalse_1"
GOTOL TSTRING "forever_end_1"
GOTOL TSTRING "top_end_1"
LBL TSTRING "top_end_1"
POP TVOID 0V
PRINTLN TSTRING "Hello!"
DEC TVOID 0V
SWITCH TVOID 0V
GOTOL TSTRING "forever_1"
LBL TSTRING "forever_end_1"
SWITCH TVOID 0V
PRINT TSTRING "Counter is output: "
PRINTLN TVOID 0V
QUIT TVOID 0


END TVOID 0V