VERSION TVOID 0V


ALOAD TNUMBER 1
ATOC TVOID 0V
ALOAD TNUMBER 6
LBL TSTRING "while_test_1"
SWITCH TVOID 0V
PUSH TVOID 0V
LSS TVOID 0V
CGOTOL TSTRING "while_body_1"
GOTOL TSTRING "while_end_1"
LBL TSTRING "while_body_1"
POP TVOID 0V
PRINT TSTRING "%accumulator = "
PRINTLN TVOID 0V
INC TVOID 0V
SWITCH TVOID 0V
GOTOL TSTRING "while_test_1"
LBL TSTRING "while_end_1"
QUIT TVOID 0


END TVOID 0V