VERSION TVOID 0V


PRINTLN TSTRING "Implementing an array..."
ASTART TSTRING "a"
AEND TNUMBER 3
PRINTLN TSTRING "Testing load and store..."
ALOAD TSTRING "a"
APREP TSTRING "a"
AIPREP TNUMBER 0
STOREIA TVOID 0V
ALOAD TSTRING "b"
APREP TSTRING "a"
AIPREP TNUMBER 1
STOREIA TVOID 0V
ALOAD TSTRING "c"
APREP TSTRING "a"
AIPREP TNUMBER 2
STOREIA TVOID 0V
PRINT TSTRING "a[0]: "
APREP TSTRING "a"
AIPREP TNUMBER 0
LOADIA TVOID 0V
PRINTLN TVOID 0V
PRINT TSTRING "a[1]: "
APREP TSTRING "a"
AIPREP TNUMBER 1
LOADIA TVOID 0V
PRINTLN TVOID 0V
PRINT TSTRING "a[2]: "
APREP TSTRING "a"
AIPREP TNUMBER 2
LOADIA TVOID 0V
PRINTLN TVOID 0V
QUIT TVOID 0


END TVOID 0V