VERSION TVOID 0V


EXADDB TVOID 3
EXADD TVOID 0
PRINTLN TSTRING "Defining an enum..."
ESTART TSTRING "a"
ENAME TSTRING "a"
ENAME TSTRING "b"
ENAME TSTRING "c"
EEND TVOID 0V
PRINTLN TSTRING "Implementing an enum..."
ENUMS TSTRING "a"
ENUM TSTRING "c"
SENUM TSTRING "a"
PRINTLN TSTRING "Testing load and store..."
PRINT TSTRING "enum a: "
EPREP TSTRING "a"
LOADE TVOID 0V
PRINTLN TVOID 0V
ALOAD TSTRING "and"
EPREP TSTRING "a"
STOREE TVOID 0V
PRINT TSTRING "enum a: "
EPREP TSTRING "a"
LOADE TVOID 0V
PRINTLN TVOID 0V
PRINTLN TSTRING "Quitting..."
QUIT TVOID 0
ELBL TVOID 0V
CRASH TSTRING "Enum event..."RET TVOID 0V


END TVOID 0V