VERSION TVOID 0V


VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
PRINT TNUMBER 32
PRINT TNUMBER 0
PRINTLN TNUMBER 32
PRINTLN TNUMBER 32
PRINTLN TVOID 0V
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TCHARACTER 'c'
QUIT TVOID 0

END TVOID 0V