VERSION TVOID 0V


VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
PRINT TNUMBER 51
PRINT TNUMBER 0
PRINTLN TNUMBER 51
PRINTLN TNUMBER 32
PRINTLN TVOID 0V
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TCHARACTER 'c'
PRINTLN TSTRING "Hello World!"
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN false
QUIT TVOID 0

END TVOID 0V