VERSION TVOID 0V


ALOAD TNUMBER 0
VSTORE TVOID 0V
FOMODE TSTRING "out"
FOOPEN TSTRING "fileio.txt"
FPRINTLN TSTRING "Hello World!"
FOCLOSE TVOID 0V
FIMODE TSTRING "in"
FIOPEN TSTRING "fileio.txt"
FREAD TSTRING 0V
ATOC TVOID 0V
VADD TVOID 0
SWITCH TVOID 0V
STOREA TVOID 0V
PRINTLN TVOID 0V
QUIT TVOID 0


END TVOID 0V