VERSION TVOID 0V


ESTART TSTRING "days_of_week"
ENAME TSTRING "Sunday"
EEND TVOID 0V
ENUMS TSTRING "days_of_week"
ENUM TSTRING "Sunday"
SENUM TSTRING "day"
ASTART TSTRING "a"
AEND TNUMBER 7
EPREP TSTRING "day"
LOADE TVOID 0V
APREP TSTRING "a"
AIPREP TNUMBER 0
STOREIA TVOID 0V
ALOAD TSTRING "Monday"
APREP TSTRING "a"
AIPREP TNUMBER 1
STOREIA TVOID 0V
ALOAD TSTRING "Tuesday"
APREP TSTRING "a"
AIPREP TNUMBER 2
STOREIA TVOID 0V
ALOAD TSTRING "Wednesday"
APREP TSTRING "a"
AIPREP TNUMBER 3
STOREIA TVOID 0V
ALOAD TSTRING "Thursday"
APREP TSTRING "a"
AIPREP TNUMBER 4
STOREIA TVOID 0V
ALOAD TSTRING "Friday"
APREP TSTRING "a"
AIPREP TNUMBER 5
STOREIA TVOID 0V
ALOAD TSTRING "Saturday"
APREP TSTRING "a"
AIPREP TNUMBER 6
STOREIA TVOID 0V
APREP TSTRING "a"
APRINT TVOID 0V
QUIT TVOID 0


END TVOID 0V