VERSION TVOID 0V


ALOAD TNUMBER 0
VSTORE TVOID 0V
PRINT TSTRING "How many hellos?: "
READ TNUMBER 0V
ATOC TVOID 0V
VADD TVOID 0
SWITCH TVOID 0V
STOREA TVOID 0V
ATOC TVOID 0V
ALOAD TNUMBER 0
GOTOL TSTRING "dofor_initialization_1"
LBL TSTRING "dofor_body_1"
POP TVOID 0V
PRINTLN TSTRING "Hello!"
GOTOL TSTRING "dofor_increment_statement_1"
LBL TSTRING "dofor_initialization_1"
SWITCH TVOID 0V
PUSH TVOID 0V
GOTOL TSTRING "dofor_body_1"
LBL TSTRING "dofor_condition_1"
SWITCH TVOID 0V
PUSH TVOID 0V
GTR TVOID 0V
CGOTOL TSTRING "dofor_body_1"
GOTOL TSTRING "dofor_end_1"
LBL TSTRING "dofor_increment_statement_1"
DEC TVOID 0V
SWITCH TVOID 0V
GOTOL TSTRING "dofor_condition_1"
LBL TSTRING "dofor_end_1"
SWITCH TVOID 0V
PRINT TSTRING "Counter is output: "
PRINTLN TVOID 0V
QUIT TVOID 0


END TVOID 0V