VERSION TVOID 0V


ESTART TSTRING "days_of_week"
ENAME TSTRING "Sunday"
EEND TVOID 0V
ENUMS TSTRING "days_of_week"
ENUM TSTRING "Sunday"
SENUM TSTRING "a"
EPREP TSTRING "a"
LOADE TVOID 0V
PRINT TSTRING "a: "
PRINTLN TVOID 0V
QUIT TVOID 0


END TVOID 0V