VERSION TVOID 0V


RDSTART1 TSTRING "a"
RFROM1 TNUMBER 5
RTO1 TNUMBER 7
RDEND1 TVOID 0V
RSTART1 TSTRING "a"
RANGE1 TNUMBER 6
REND1 TSTRING "a"
RLOAD1 TSTRING "a"
PRINT TSTRING "The value of the type1 range is: "
PRINTLN TVOID 0V
RDSTART2 TSTRING "b"
RFROM2 TNUMBER 3
RTO2 TNUMBER 7
RDEND2 TVOID 0V
RSTART2 TSTRING "b"
RANGE2 TSTRING "b"
RPREP2 TSTRING "b"
RLOAD2 TNUMBER 2
PRINT TSTRING "The 2nd index of the type2 range is: "
PRINTLN TVOID 0V
QUIT TVOID 0


END TVOID 0V