VERSION TVOID 0V


ALOAD TSTRING "Dennis Earl Smiley"
VSTORE TVOID 0V
ALOAD TNUMBER 31
VSTORE TVOID 0V
PRINT TSTRING "My name is: "
PRINT TSTRING "Dennis Earl Smiley"
PRINTLN TSTRING "."
PRINT TSTRING "My age is: "
PRINT TNUMBER 31
PRINTLN TSTRING "."
QUIT TVOID 0


END TVOID 0V