VERSION TVOID 0V


VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
PRINT TNUMBER 32
PRINT TNUMBER 0
PRINTLN TNUMBER 32
PRINTLN TNUMBER  
PRINTLN TVOID 0V
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TCHARACTER 'c'
PRINTLN TSTRING "Hello World!"
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TNUMBER 4
PRINTLN TNUMBER 2
PRINTLN TNUMBER 3
PRINTLN TNUMBER 3
PRINTLN TNUMBER 2
PRINTLN TNUMBER 3
PRINTLN TNUMBER 4
QUIT TVOID 

END TVOID 0V