VERSION TVOID 0V


ALOAD TBOOLEAN true
VSTORE TVOID 0V
PRINTLN TBOOLEAN false
ALOAD TBOOLEAN false
VSTORE TVOID 0V
ALOAD TBOOLEAN false
VSTORE TVOID 0V
ALOAD TBOOLEAN false
VSTORE TVOID 0V
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN false
QUIT TVOID 0

END TVOID 0V