VERSION TVOID 0V


ALOAD TNUMBER 1
VSTORE TVOID 0V
ALOAD TNUMBER 2
VSTORE TVOID 0V
PRINTLN TNUMBER 1
PRINTLN TNUMBER 2
ALOAD TNUMBER 3
VSTORE TVOID 0V
PRINTLN TNUMBER 3
PRINTLN TNUMBER -3
ALOAD TNUMBER -3
VSTORE TVOID 0V
PRINTLN TNUMBER -3
QUIT TVOID 0

END TVOID 0V