VERSION TVOID 0V


PRINTLN TSTRING "Defining an array..."
ASTART TSTRING "a"
AINDEX TVOID 0V
VAR TNUMBER 0
AINDEXE TVOID 0V

AINDEX TVOID 0V
VAR TNUMBER 1
AINDEXE TVOID 0V
AEND TVOID 0V


PRINTLN TSTRING "Testing load and store..."
PRINT TSTRING "a[1]: "
VLOAD TNUMBER 1
PRINTLN TVOID 0V


PRINTLN TSTRING "Quitting..."
QUIT TVOID 0


END TVOID 0V