VERSION TVOID 0V


PRINTLN TSTRING "Outside of exception."
EXADD TVOID 0
EXCEPTION TVOID 0
PRINTLN TSTRING "Back outside of exception."
QUIT TVOID 0
ELBL TVOID 0V
PRINTLN TSTRING "Inside of exception."
RET TVOID 0V

END TVOID 0V