VERSION TVOID 0V


CALLL TVOID 0
QUIT TVOID 0
LBL TVOID 0V
ISUPP TNUMBER 89
CGOTOL TSTRING "patch_supp"
GOTOL TSTRING "patch_no_supp"
LBL TSTRING "patch_supp"
PATCH TVOID 0V
GOTOL TSTRING "patch_end"
LBL TSTRING "patch_no_supp"
CRASH TSTRING "PATCH not supported."GOTOL TSTRING "patch_end"
LBL TSTRING "patch_end"
RET TVOID 0V


END TVOID 0V