VERSION TVOID 1


STRUCT TSTRING "a"
STRUCTVAR TSTRING "a"
STRUCTVAR TSTRING "b"
ENDSTRUCT TVOID 0V

STRUCTNAME TSTRING "a"
STRUCTD TSTRING "ainst"

STRUCTONAME TSTRING "ainst"
STRUCTUSE TSTRING "b"

STRUCTUSING TVOID 0V
PRINTLN TVOID 0V
STRUCTUSE TNUMBER 0V
STRUCTUSING TVOID 0V
PRINTLN TVOID 0V


ALOAD TSTRING "Hello World!"
STRUCTPUT TVOID 0V

ALOAD TSTRING "a"
PRINTLN TVOID 0V
PRINT TSTRING "("
STRUCTTYPE TVOID 0V
PRINT TVOID 0V
PRINT TSTRING ") "
STRUCTNAME2 TVOID 0V
PRINT TVOID 0V
PRINT TSTRING "."
STRUCTUSINGNAME TVOID 0V
PRINT TVOID 0V
PRINT TSTRING ": "
STRUCTGET TVOID 0V
PRINTLN TVOID 0V

QUIT TVOID 0


END TVOID 0V
