VERSION TVOID 1


ALOAD TNUMBER 22
SWITCH TVOID 0V
ALOAD TNUMBER 22
SWITCH TVOID 0V
EQU TVOID 0V
NOT TVOID 0V
IF TVOID 0V
IFBEGIN TVOID 0V
PRINTLN TSTRING "false"
IFEND TVOID 0V
ENDIF TVOID 0V
IFELSE TVOID 0V
IFBEGIN TVOID 0V
PRINTLN TSTRING "true"
IFEND TVOID 0V
ENDIFELSE TVOID 0V
EIF TVOID 0V
ALOAD TNUMBER 22
SWITCH TVOID 0V
ALOAD TNUMBER 22
SWITCH TVOID 0V
EQU TVOID 0V
IF TVOID 0V
IFBEGIN TVOID 0V
PRINTLN TSTRING "false"
IFEND TVOID 0V
ENDIF TVOID 0V
IFELSE TVOID 0V
IFBEGIN TVOID 0V
PRINTLN TSTRING "true"
IFEND TVOID 0V
ENDIFELSE TVOID 0V
EIF TVOID 0V
QUIT TVOID 0


END TVOID 0V