VERSION TVOID 0V


ALOAD TNUMBER 5
VSTORE TVOID 0V
VLOAD TNUMBER 0
INC TVOID 0V
ATOC TVOID 0V
ALOAD TNUMBER 5
SWITCH TVOID 0V
EQU TVOID 0V
IF TVOID 0V
IFBEGIN TVOID 0V
PRINT TSTRING "a = "
PRINTLN TNUMBER 5
IFEND TVOID 0V
ENDIF TVOID 0V
IFELSE TVOID 0V
IFBEGIN TVOID 0V
PRINTLN TSTRING "Other value."
IFEND TVOID 0V
ENDIFELSE TVOID 0V
EIF TVOID 0V
VLOAD TNUMBER 0
ATOC TVOID 0V
ALOAD TNUMBER 5
SWITCH TVOID 0V
EQU TVOID 0V
IF TVOID 0V
IFBEGIN TVOID 0V
VLOAD TNUMBER 1
PRINT TSTRING "a = "
PRINTLN TVOID 0V
IFEND TVOID 0V
ENDIF TVOID 0V
IFELSE TVOID 0V
IFBEGIN TVOID 0V
PRINTLN TSTRING "Other value."
IFEND TVOID 0V
ENDIFELSE TVOID 0V
EIF TVOID 0V
QUIT TVOID 0


END TVOID 0V