VERSION TVOID 0V


EXADDB TVOID 3
EXADD TVOID 0


PRINTLN TSTRING "Defining an enum..."
ESTART TSTRING "al"
ENAME TSTRING "a"
ENAME TSTRING "b"
ENAME TSTRING "c"
ENAME TSTRING "d"
EEND TVOID 0V


PRINTLN TSTRING "Implementing an enum..."
ENUMS TSTRING "al"
ENUM TSTRING "c"
SENUM TSTRING "a"


PRINTLN TSTRING "Testing load and store..."
EPREP TSTRING "a"
LOADE TVOID 0V
PRINT TSTRING "Enum a is: "
PRINTLN TVOID 0V

PRINT TSTRING "Enter a letter between a and d: "
READ TSTRING 0V
EPREP TSTRING "a"
STOREE TVOID 0V

EPREP TSTRING "a"
LOADE TVOID 0V
PRINT TSTRING "Your choice was: "
PRINTLN TVOID 0V


PRINTLN TSTRING "Quitting..."
QUIT TVOID 0


ELBL TVOID 0V
RET TVOID 0V


END TVOID 0V