VERSION TVOID 0V


PRINTLN TNUMBER 32
ALOAD TNUMBER 0
VSTORE TVOID 0V
PRINTLN TNUMBER 0
ALOAD TNUMBER 33
VSTORE TVOID 0V
PRINTLN TNUMBER 33
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN true
QUIT TVOID 0


END TVOID 0V