VERSION TVOID 0V


VOID TVOID 0V
ALOAD TNUMBER 0
VSTORE TVOID 0V
ALOAD TNUMBER 2
VSTORE TVOID 0V
ALOAD TNUMBER 33
VSTORE TVOID 0V
ALOAD TNUMBER 33
VSTORE TVOID 0V
ALOAD TNUMBER 3
VSTORE TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
VOID TVOID 0V
PRINT TNUMBER 32
PRINT TNUMBER 0
PRINTLN TNUMBER 32
PRINTLN TNUMBER 32
ALOAD TNUMBER 0
VSTORE TVOID 0V
ALOAD TNUMBER 0
VSTORE TVOID 0V
PRINTLN TBOOLEAN true
PRINTLN TBOOLEAN false
PRINTLN TCHARACTER 'c'
PRINTLN TSTRING "Hello World!"
ALOAD TBOOLEAN false
VSTORE TVOID 0V
PRINTLN TBOOLEAN false
ALOAD TBOOLEAN false
VSTORE TVOID 0V
PRINTLN TBOOLEAN false
PRINTLN TBOOLEAN true
QUIT TVOID 0


END TVOID 0V