VERSION TVOID 0V


ALOAD TSTRING ""
VSTORE TVOID 0V
PRINT TSTRING "Enter a name: "
READ TSTRING 0V
ATOC TVOID 0V
VADD TVOID 0
SWITCH TVOID 0V
STOREA TVOID 0V
VLOAD TSTRING 0
SWITCH2 TVOID 0V
SWBEGIN TVOID 0V
ALOAD TSTRING "Dennis"
SWCASE TVOID 0V
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Cool name!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
ALOAD TSTRING "Amy"
SWCASE TVOID 0V
SWCBEGIN TVOID 0V
PRINTLN TSTRING "That's my sister!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
ALOAD TSTRING "Michael"
SWCASE TVOID 0V
SWCBEGIN TVOID 0V
PRINTLN TSTRING "He's my friend!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWDEFAULT TVOID 0V
SWCBEGIN TVOID 0V
PRINTLN TSTRING "I didn't recognize the name."
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWEND TVOID 0V
QUIT TVOID 0


END TVOID 0V