VERSION TVOID 0V


ALOAD TSTRING "Dennis"
VSTORE TVOID 0V
ALOAD TSTRING "Dennis"
SWITCH2 TVOID 0V
SWBEGIN TVOID 0V
SWCASE TSTRING "Dennis"
SWCBEGIN TVOID 0V
PRINTLN TSTRING "Cool name!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWCASE TSTRING "Amy"
SWCBEGIN TVOID 0V
PRINTLN TSTRING "That's my sister!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWCASE TSTRING "Michael"
SWCBEGIN TVOID 0V
PRINTLN TSTRING "He's my friend!"
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWDEFAULT TVOID 0V
SWCBEGIN TVOID 0V
PRINTLN TSTRING "I didn't recognize the name."
SWBREAK TVOID 0V
SWCEND TVOID 0V
SWEND TVOID 0V
QUIT TVOID 0


END TVOID 0V