VERSION TVOID 0V


VSUPP TVOID 0
CGOTOL TSTRING "v1_supp"
GOTOL TSTRING "v1_nsupp"

LBL TSTRING "v1_supp"
PRINTLN TSTRING "v1 supported."
GOTOL TSTRING "end"

LBL TSTRING "v1_nsupp"
PRINTLN TSTRING "v1 unsupported."
GOTOL TSTRING "end"

LBL TSTRING "end"
PRINT TSTRING "In v1? "
VCHECK TVOID 0
PRINTLN TVOID 0V
PRINT TSTRING "version: "
VPRINT TVOID 0V
QUIT TVOID 0


END TVOID 0V