VERSION TVOID 1


PRINT TSTRING "?"
READ TNUMBER 0V
VSTORE TVOID 0V
LBL TSTRING "loop"
PRINT TSTRING "?"
READ TNUMBER 0V
VSTORE TVOID 0V
PRINT TSTRING "?"
READ TNUMBER 0V
VSTORE TVOID 0V
VLOAD TNUMBER 1
MUL TNUMBER 2
VSTORE TVOID 0V
VLOAD TNUMBER 2
MUL TNUMBER 3
ADD TNUMBER 4
VSTORE TVOID 0V
VLOAD TNUMBER 1
PRINTLN TVOID 0V
VLOAD TNUMBER 2
PRINTLN TVOID 0V
VLOAD TNUMBER 4
PRINTLN TVOID 0V
ST TVOID 0V
CGOTOL TSTRING "loop"
QUIT TVOID 0


END TVOID 0V